// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/agent/lib"
	"github.com/bborbe/agent/prompt/controller/pkg/publisher"
)

type FakePromptPublisher struct {
	PublishPromptStub        func(context.Context, lib.Prompt) error
	publishPromptMutex       sync.RWMutex
	publishPromptArgsForCall []struct {
		arg1 context.Context
		arg2 lib.Prompt
	}
	publishPromptReturns struct {
		result1 error
	}
	publishPromptReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakePromptPublisher) PublishPrompt(arg1 context.Context, arg2 lib.Prompt) error {
	fake.publishPromptMutex.Lock()
	ret, specificReturn := fake.publishPromptReturnsOnCall[len(fake.publishPromptArgsForCall)]
	fake.publishPromptArgsForCall = append(fake.publishPromptArgsForCall, struct {
		arg1 context.Context
		arg2 lib.Prompt
	}{arg1, arg2})
	stub := fake.PublishPromptStub
	fakeReturns := fake.publishPromptReturns
	fake.recordInvocation("PublishPrompt", []interface{}{arg1, arg2})
	fake.publishPromptMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePromptPublisher) PublishPromptCallCount() int {
	fake.publishPromptMutex.RLock()
	defer fake.publishPromptMutex.RUnlock()
	return len(fake.publishPromptArgsForCall)
}

func (fake *FakePromptPublisher) PublishPromptCalls(stub func(context.Context, lib.Prompt) error) {
	fake.publishPromptMutex.Lock()
	defer fake.publishPromptMutex.Unlock()
	fake.PublishPromptStub = stub
}

func (fake *FakePromptPublisher) PublishPromptArgsForCall(i int) (context.Context, lib.Prompt) {
	fake.publishPromptMutex.RLock()
	defer fake.publishPromptMutex.RUnlock()
	argsForCall := fake.publishPromptArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakePromptPublisher) PublishPromptReturns(result1 error) {
	fake.publishPromptMutex.Lock()
	defer fake.publishPromptMutex.Unlock()
	fake.PublishPromptStub = nil
	fake.publishPromptReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePromptPublisher) PublishPromptReturnsOnCall(i int, result1 error) {
	fake.publishPromptMutex.Lock()
	defer fake.publishPromptMutex.Unlock()
	fake.PublishPromptStub = nil
	if fake.publishPromptReturnsOnCall == nil {
		fake.publishPromptReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.publishPromptReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePromptPublisher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakePromptPublisher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ publisher.PromptPublisher = new(FakePromptPublisher)
