// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/bborbe/agent/lib"
	"github.com/bborbe/agent/task/executor/pkg/handler"
)

type FakeDuplicateTracker struct {
	IsDuplicateStub        func(lib.TaskIdentifier) bool
	isDuplicateMutex       sync.RWMutex
	isDuplicateArgsForCall []struct {
		arg1 lib.TaskIdentifier
	}
	isDuplicateReturns struct {
		result1 bool
	}
	isDuplicateReturnsOnCall map[int]struct {
		result1 bool
	}
	MarkProcessedStub        func(lib.TaskIdentifier)
	markProcessedMutex       sync.RWMutex
	markProcessedArgsForCall []struct {
		arg1 lib.TaskIdentifier
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDuplicateTracker) IsDuplicate(arg1 lib.TaskIdentifier) bool {
	fake.isDuplicateMutex.Lock()
	ret, specificReturn := fake.isDuplicateReturnsOnCall[len(fake.isDuplicateArgsForCall)]
	fake.isDuplicateArgsForCall = append(fake.isDuplicateArgsForCall, struct {
		arg1 lib.TaskIdentifier
	}{arg1})
	stub := fake.IsDuplicateStub
	fakeReturns := fake.isDuplicateReturns
	fake.recordInvocation("IsDuplicate", []interface{}{arg1})
	fake.isDuplicateMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDuplicateTracker) IsDuplicateCallCount() int {
	fake.isDuplicateMutex.RLock()
	defer fake.isDuplicateMutex.RUnlock()
	return len(fake.isDuplicateArgsForCall)
}

func (fake *FakeDuplicateTracker) IsDuplicateCalls(stub func(lib.TaskIdentifier) bool) {
	fake.isDuplicateMutex.Lock()
	defer fake.isDuplicateMutex.Unlock()
	fake.IsDuplicateStub = stub
}

func (fake *FakeDuplicateTracker) IsDuplicateArgsForCall(i int) lib.TaskIdentifier {
	fake.isDuplicateMutex.RLock()
	defer fake.isDuplicateMutex.RUnlock()
	argsForCall := fake.isDuplicateArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeDuplicateTracker) IsDuplicateReturns(result1 bool) {
	fake.isDuplicateMutex.Lock()
	defer fake.isDuplicateMutex.Unlock()
	fake.IsDuplicateStub = nil
	fake.isDuplicateReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeDuplicateTracker) IsDuplicateReturnsOnCall(i int, result1 bool) {
	fake.isDuplicateMutex.Lock()
	defer fake.isDuplicateMutex.Unlock()
	fake.IsDuplicateStub = nil
	if fake.isDuplicateReturnsOnCall == nil {
		fake.isDuplicateReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.isDuplicateReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeDuplicateTracker) MarkProcessed(arg1 lib.TaskIdentifier) {
	fake.markProcessedMutex.Lock()
	fake.markProcessedArgsForCall = append(fake.markProcessedArgsForCall, struct {
		arg1 lib.TaskIdentifier
	}{arg1})
	stub := fake.MarkProcessedStub
	fake.recordInvocation("MarkProcessed", []interface{}{arg1})
	fake.markProcessedMutex.Unlock()
	if stub != nil {
		fake.MarkProcessedStub(arg1)
	}
}

func (fake *FakeDuplicateTracker) MarkProcessedCallCount() int {
	fake.markProcessedMutex.RLock()
	defer fake.markProcessedMutex.RUnlock()
	return len(fake.markProcessedArgsForCall)
}

func (fake *FakeDuplicateTracker) MarkProcessedCalls(stub func(lib.TaskIdentifier)) {
	fake.markProcessedMutex.Lock()
	defer fake.markProcessedMutex.Unlock()
	fake.MarkProcessedStub = stub
}

func (fake *FakeDuplicateTracker) MarkProcessedArgsForCall(i int) lib.TaskIdentifier {
	fake.markProcessedMutex.RLock()
	defer fake.markProcessedMutex.RUnlock()
	argsForCall := fake.markProcessedArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeDuplicateTracker) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeDuplicateTracker) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ handler.DuplicateTracker = new(FakeDuplicateTracker)
