// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/agent/lib"
	"github.com/bborbe/agent/task/executor/pkg/spawner"
)

type FakeJobSpawner struct {
	SpawnJobStub        func(context.Context, lib.Task, string) error
	spawnJobMutex       sync.RWMutex
	spawnJobArgsForCall []struct {
		arg1 context.Context
		arg2 lib.Task
		arg3 string
	}
	spawnJobReturns struct {
		result1 error
	}
	spawnJobReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeJobSpawner) SpawnJob(arg1 context.Context, arg2 lib.Task, arg3 string) error {
	fake.spawnJobMutex.Lock()
	ret, specificReturn := fake.spawnJobReturnsOnCall[len(fake.spawnJobArgsForCall)]
	fake.spawnJobArgsForCall = append(fake.spawnJobArgsForCall, struct {
		arg1 context.Context
		arg2 lib.Task
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.SpawnJobStub
	fakeReturns := fake.spawnJobReturns
	fake.recordInvocation("SpawnJob", []interface{}{arg1, arg2, arg3})
	fake.spawnJobMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeJobSpawner) SpawnJobCallCount() int {
	fake.spawnJobMutex.RLock()
	defer fake.spawnJobMutex.RUnlock()
	return len(fake.spawnJobArgsForCall)
}

func (fake *FakeJobSpawner) SpawnJobCalls(stub func(context.Context, lib.Task, string) error) {
	fake.spawnJobMutex.Lock()
	defer fake.spawnJobMutex.Unlock()
	fake.SpawnJobStub = stub
}

func (fake *FakeJobSpawner) SpawnJobArgsForCall(i int) (context.Context, lib.Task, string) {
	fake.spawnJobMutex.RLock()
	defer fake.spawnJobMutex.RUnlock()
	argsForCall := fake.spawnJobArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeJobSpawner) SpawnJobReturns(result1 error) {
	fake.spawnJobMutex.Lock()
	defer fake.spawnJobMutex.Unlock()
	fake.SpawnJobStub = nil
	fake.spawnJobReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeJobSpawner) SpawnJobReturnsOnCall(i int, result1 error) {
	fake.spawnJobMutex.Lock()
	defer fake.spawnJobMutex.Unlock()
	fake.SpawnJobStub = nil
	if fake.spawnJobReturnsOnCall == nil {
		fake.spawnJobReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.spawnJobReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeJobSpawner) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeJobSpawner) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ spawner.JobSpawner = new(FakeJobSpawner)
