// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/agent/task/executor/pkg"
	v1 "k8s.io/api/batch/v1"
)

type FakeJobWatcher struct {
	HandleJobStub        func(context.Context, *v1.Job)
	handleJobMutex       sync.RWMutex
	handleJobArgsForCall []struct {
		arg1 context.Context
		arg2 *v1.Job
	}
	RunStub        func(context.Context) error
	runMutex       sync.RWMutex
	runArgsForCall []struct {
		arg1 context.Context
	}
	runReturns struct {
		result1 error
	}
	runReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeJobWatcher) HandleJob(arg1 context.Context, arg2 *v1.Job) {
	fake.handleJobMutex.Lock()
	fake.handleJobArgsForCall = append(fake.handleJobArgsForCall, struct {
		arg1 context.Context
		arg2 *v1.Job
	}{arg1, arg2})
	stub := fake.HandleJobStub
	fake.recordInvocation("HandleJob", []interface{}{arg1, arg2})
	fake.handleJobMutex.Unlock()
	if stub != nil {
		fake.HandleJobStub(arg1, arg2)
	}
}

func (fake *FakeJobWatcher) HandleJobCallCount() int {
	fake.handleJobMutex.RLock()
	defer fake.handleJobMutex.RUnlock()
	return len(fake.handleJobArgsForCall)
}

func (fake *FakeJobWatcher) HandleJobCalls(stub func(context.Context, *v1.Job)) {
	fake.handleJobMutex.Lock()
	defer fake.handleJobMutex.Unlock()
	fake.HandleJobStub = stub
}

func (fake *FakeJobWatcher) HandleJobArgsForCall(i int) (context.Context, *v1.Job) {
	fake.handleJobMutex.RLock()
	defer fake.handleJobMutex.RUnlock()
	argsForCall := fake.handleJobArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeJobWatcher) Run(arg1 context.Context) error {
	fake.runMutex.Lock()
	ret, specificReturn := fake.runReturnsOnCall[len(fake.runArgsForCall)]
	fake.runArgsForCall = append(fake.runArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.RunStub
	fakeReturns := fake.runReturns
	fake.recordInvocation("Run", []interface{}{arg1})
	fake.runMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeJobWatcher) RunCallCount() int {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return len(fake.runArgsForCall)
}

func (fake *FakeJobWatcher) RunCalls(stub func(context.Context) error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = stub
}

func (fake *FakeJobWatcher) RunArgsForCall(i int) context.Context {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	argsForCall := fake.runArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeJobWatcher) RunReturns(result1 error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = nil
	fake.runReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeJobWatcher) RunReturnsOnCall(i int, result1 error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = nil
	if fake.runReturnsOnCall == nil {
		fake.runReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.runReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeJobWatcher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeJobWatcher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.JobWatcher = new(FakeJobWatcher)
