// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1 "github.com/bborbe/agent/task/executor/k8s/apis/agents.bborbe.dev/v1"
	agentsbborbedevv1 "github.com/bborbe/agent/task/executor/k8s/client/applyconfiguration/agents.bborbe.dev/v1"
	internal "github.com/bborbe/agent/task/executor/k8s/client/applyconfiguration/internal"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=agents.bborbe.dev, Version=v1
	case v1.SchemeGroupVersion.WithKind("AgentConfig"):
		return &agentsbborbedevv1.AgentConfigApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("AgentConfigSpec"):
		return &agentsbborbedevv1.AgentConfigSpecApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("AgentResources"):
		return &agentsbborbedevv1.AgentResourcesApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
