// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/agent/claude"
)

type ClaudePermissionDecider struct {
	DecidePermissionStub        func(context.Context, claude.PermissionRequest) (claude.PermissionDecision, error)
	decidePermissionMutex       sync.RWMutex
	decidePermissionArgsForCall []struct {
		arg1 context.Context
		arg2 claude.PermissionRequest
	}
	decidePermissionReturns struct {
		result1 claude.PermissionDecision
		result2 error
	}
	decidePermissionReturnsOnCall map[int]struct {
		result1 claude.PermissionDecision
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ClaudePermissionDecider) DecidePermission(arg1 context.Context, arg2 claude.PermissionRequest) (claude.PermissionDecision, error) {
	fake.decidePermissionMutex.Lock()
	ret, specificReturn := fake.decidePermissionReturnsOnCall[len(fake.decidePermissionArgsForCall)]
	fake.decidePermissionArgsForCall = append(fake.decidePermissionArgsForCall, struct {
		arg1 context.Context
		arg2 claude.PermissionRequest
	}{arg1, arg2})
	stub := fake.DecidePermissionStub
	fakeReturns := fake.decidePermissionReturns
	fake.recordInvocation("DecidePermission", []interface{}{arg1, arg2})
	fake.decidePermissionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ClaudePermissionDecider) DecidePermissionCallCount() int {
	fake.decidePermissionMutex.RLock()
	defer fake.decidePermissionMutex.RUnlock()
	return len(fake.decidePermissionArgsForCall)
}

func (fake *ClaudePermissionDecider) DecidePermissionCalls(stub func(context.Context, claude.PermissionRequest) (claude.PermissionDecision, error)) {
	fake.decidePermissionMutex.Lock()
	defer fake.decidePermissionMutex.Unlock()
	fake.DecidePermissionStub = stub
}

func (fake *ClaudePermissionDecider) DecidePermissionArgsForCall(i int) (context.Context, claude.PermissionRequest) {
	fake.decidePermissionMutex.RLock()
	defer fake.decidePermissionMutex.RUnlock()
	argsForCall := fake.decidePermissionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ClaudePermissionDecider) DecidePermissionReturns(result1 claude.PermissionDecision, result2 error) {
	fake.decidePermissionMutex.Lock()
	defer fake.decidePermissionMutex.Unlock()
	fake.DecidePermissionStub = nil
	fake.decidePermissionReturns = struct {
		result1 claude.PermissionDecision
		result2 error
	}{result1, result2}
}

func (fake *ClaudePermissionDecider) DecidePermissionReturnsOnCall(i int, result1 claude.PermissionDecision, result2 error) {
	fake.decidePermissionMutex.Lock()
	defer fake.decidePermissionMutex.Unlock()
	fake.DecidePermissionStub = nil
	if fake.decidePermissionReturnsOnCall == nil {
		fake.decidePermissionReturnsOnCall = make(map[int]struct {
			result1 claude.PermissionDecision
			result2 error
		})
	}
	fake.decidePermissionReturnsOnCall[i] = struct {
		result1 claude.PermissionDecision
		result2 error
	}{result1, result2}
}

func (fake *ClaudePermissionDecider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ClaudePermissionDecider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ claude.PermissionDecider = new(ClaudePermissionDecider)
