// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/agent/claude"
	"github.com/bborbe/agent/interactive"
)

type InteractivePermissionRegistry struct {
	DecidePermissionStub        func(context.Context, claude.PermissionRequest) (claude.PermissionDecision, error)
	decidePermissionMutex       sync.RWMutex
	decidePermissionArgsForCall []struct {
		arg1 context.Context
		arg2 claude.PermissionRequest
	}
	decidePermissionReturns struct {
		result1 claude.PermissionDecision
		result2 error
	}
	decidePermissionReturnsOnCall map[int]struct {
		result1 claude.PermissionDecision
		result2 error
	}
	ListStub        func() []interactive.PendingPermission
	listMutex       sync.RWMutex
	listArgsForCall []struct {
	}
	listReturns struct {
		result1 []interactive.PendingPermission
	}
	listReturnsOnCall map[int]struct {
		result1 []interactive.PendingPermission
	}
	ResolveStub        func(string, claude.PermissionDecision) bool
	resolveMutex       sync.RWMutex
	resolveArgsForCall []struct {
		arg1 string
		arg2 claude.PermissionDecision
	}
	resolveReturns struct {
		result1 bool
	}
	resolveReturnsOnCall map[int]struct {
		result1 bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *InteractivePermissionRegistry) DecidePermission(arg1 context.Context, arg2 claude.PermissionRequest) (claude.PermissionDecision, error) {
	fake.decidePermissionMutex.Lock()
	ret, specificReturn := fake.decidePermissionReturnsOnCall[len(fake.decidePermissionArgsForCall)]
	fake.decidePermissionArgsForCall = append(fake.decidePermissionArgsForCall, struct {
		arg1 context.Context
		arg2 claude.PermissionRequest
	}{arg1, arg2})
	stub := fake.DecidePermissionStub
	fakeReturns := fake.decidePermissionReturns
	fake.recordInvocation("DecidePermission", []interface{}{arg1, arg2})
	fake.decidePermissionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *InteractivePermissionRegistry) DecidePermissionCallCount() int {
	fake.decidePermissionMutex.RLock()
	defer fake.decidePermissionMutex.RUnlock()
	return len(fake.decidePermissionArgsForCall)
}

func (fake *InteractivePermissionRegistry) DecidePermissionCalls(stub func(context.Context, claude.PermissionRequest) (claude.PermissionDecision, error)) {
	fake.decidePermissionMutex.Lock()
	defer fake.decidePermissionMutex.Unlock()
	fake.DecidePermissionStub = stub
}

func (fake *InteractivePermissionRegistry) DecidePermissionArgsForCall(i int) (context.Context, claude.PermissionRequest) {
	fake.decidePermissionMutex.RLock()
	defer fake.decidePermissionMutex.RUnlock()
	argsForCall := fake.decidePermissionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *InteractivePermissionRegistry) DecidePermissionReturns(result1 claude.PermissionDecision, result2 error) {
	fake.decidePermissionMutex.Lock()
	defer fake.decidePermissionMutex.Unlock()
	fake.DecidePermissionStub = nil
	fake.decidePermissionReturns = struct {
		result1 claude.PermissionDecision
		result2 error
	}{result1, result2}
}

func (fake *InteractivePermissionRegistry) DecidePermissionReturnsOnCall(i int, result1 claude.PermissionDecision, result2 error) {
	fake.decidePermissionMutex.Lock()
	defer fake.decidePermissionMutex.Unlock()
	fake.DecidePermissionStub = nil
	if fake.decidePermissionReturnsOnCall == nil {
		fake.decidePermissionReturnsOnCall = make(map[int]struct {
			result1 claude.PermissionDecision
			result2 error
		})
	}
	fake.decidePermissionReturnsOnCall[i] = struct {
		result1 claude.PermissionDecision
		result2 error
	}{result1, result2}
}

func (fake *InteractivePermissionRegistry) List() []interactive.PendingPermission {
	fake.listMutex.Lock()
	ret, specificReturn := fake.listReturnsOnCall[len(fake.listArgsForCall)]
	fake.listArgsForCall = append(fake.listArgsForCall, struct {
	}{})
	stub := fake.ListStub
	fakeReturns := fake.listReturns
	fake.recordInvocation("List", []interface{}{})
	fake.listMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *InteractivePermissionRegistry) ListCallCount() int {
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	return len(fake.listArgsForCall)
}

func (fake *InteractivePermissionRegistry) ListCalls(stub func() []interactive.PendingPermission) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = stub
}

func (fake *InteractivePermissionRegistry) ListReturns(result1 []interactive.PendingPermission) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = nil
	fake.listReturns = struct {
		result1 []interactive.PendingPermission
	}{result1}
}

func (fake *InteractivePermissionRegistry) ListReturnsOnCall(i int, result1 []interactive.PendingPermission) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = nil
	if fake.listReturnsOnCall == nil {
		fake.listReturnsOnCall = make(map[int]struct {
			result1 []interactive.PendingPermission
		})
	}
	fake.listReturnsOnCall[i] = struct {
		result1 []interactive.PendingPermission
	}{result1}
}

func (fake *InteractivePermissionRegistry) Resolve(arg1 string, arg2 claude.PermissionDecision) bool {
	fake.resolveMutex.Lock()
	ret, specificReturn := fake.resolveReturnsOnCall[len(fake.resolveArgsForCall)]
	fake.resolveArgsForCall = append(fake.resolveArgsForCall, struct {
		arg1 string
		arg2 claude.PermissionDecision
	}{arg1, arg2})
	stub := fake.ResolveStub
	fakeReturns := fake.resolveReturns
	fake.recordInvocation("Resolve", []interface{}{arg1, arg2})
	fake.resolveMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *InteractivePermissionRegistry) ResolveCallCount() int {
	fake.resolveMutex.RLock()
	defer fake.resolveMutex.RUnlock()
	return len(fake.resolveArgsForCall)
}

func (fake *InteractivePermissionRegistry) ResolveCalls(stub func(string, claude.PermissionDecision) bool) {
	fake.resolveMutex.Lock()
	defer fake.resolveMutex.Unlock()
	fake.ResolveStub = stub
}

func (fake *InteractivePermissionRegistry) ResolveArgsForCall(i int) (string, claude.PermissionDecision) {
	fake.resolveMutex.RLock()
	defer fake.resolveMutex.RUnlock()
	argsForCall := fake.resolveArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *InteractivePermissionRegistry) ResolveReturns(result1 bool) {
	fake.resolveMutex.Lock()
	defer fake.resolveMutex.Unlock()
	fake.ResolveStub = nil
	fake.resolveReturns = struct {
		result1 bool
	}{result1}
}

func (fake *InteractivePermissionRegistry) ResolveReturnsOnCall(i int, result1 bool) {
	fake.resolveMutex.Lock()
	defer fake.resolveMutex.Unlock()
	fake.ResolveStub = nil
	if fake.resolveReturnsOnCall == nil {
		fake.resolveReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.resolveReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *InteractivePermissionRegistry) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *InteractivePermissionRegistry) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ interactive.PermissionRegistry = new(InteractivePermissionRegistry)
