// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	lib "github.com/bborbe/agent"
)

type Session struct {
	CloseStub        func(context.Context) error
	closeMutex       sync.RWMutex
	closeArgsForCall []struct {
		arg1 context.Context
	}
	closeReturns struct {
		result1 error
	}
	closeReturnsOnCall map[int]struct {
		result1 error
	}
	PromptStub        func(context.Context, string) (string, error)
	promptMutex       sync.RWMutex
	promptArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	promptReturns struct {
		result1 string
		result2 error
	}
	promptReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Session) Close(arg1 context.Context) error {
	fake.closeMutex.Lock()
	ret, specificReturn := fake.closeReturnsOnCall[len(fake.closeArgsForCall)]
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.CloseStub
	fakeReturns := fake.closeReturns
	fake.recordInvocation("Close", []interface{}{arg1})
	fake.closeMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Session) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

func (fake *Session) CloseCalls(stub func(context.Context) error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = stub
}

func (fake *Session) CloseArgsForCall(i int) context.Context {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	argsForCall := fake.closeArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Session) CloseReturns(result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	fake.closeReturns = struct {
		result1 error
	}{result1}
}

func (fake *Session) CloseReturnsOnCall(i int, result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	if fake.closeReturnsOnCall == nil {
		fake.closeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.closeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Session) Prompt(arg1 context.Context, arg2 string) (string, error) {
	fake.promptMutex.Lock()
	ret, specificReturn := fake.promptReturnsOnCall[len(fake.promptArgsForCall)]
	fake.promptArgsForCall = append(fake.promptArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.PromptStub
	fakeReturns := fake.promptReturns
	fake.recordInvocation("Prompt", []interface{}{arg1, arg2})
	fake.promptMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Session) PromptCallCount() int {
	fake.promptMutex.RLock()
	defer fake.promptMutex.RUnlock()
	return len(fake.promptArgsForCall)
}

func (fake *Session) PromptCalls(stub func(context.Context, string) (string, error)) {
	fake.promptMutex.Lock()
	defer fake.promptMutex.Unlock()
	fake.PromptStub = stub
}

func (fake *Session) PromptArgsForCall(i int) (context.Context, string) {
	fake.promptMutex.RLock()
	defer fake.promptMutex.RUnlock()
	argsForCall := fake.promptArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Session) PromptReturns(result1 string, result2 error) {
	fake.promptMutex.Lock()
	defer fake.promptMutex.Unlock()
	fake.PromptStub = nil
	fake.promptReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *Session) PromptReturnsOnCall(i int, result1 string, result2 error) {
	fake.promptMutex.Lock()
	defer fake.promptMutex.Unlock()
	fake.PromptStub = nil
	if fake.promptReturnsOnCall == nil {
		fake.promptReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.promptReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *Session) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Session) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ lib.Session = new(Session)
