// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/agent/lib"
)

type AgentStep struct {
	NameStub        func() string
	nameMutex       sync.RWMutex
	nameArgsForCall []struct {
	}
	nameReturns struct {
		result1 string
	}
	nameReturnsOnCall map[int]struct {
		result1 string
	}
	RunStub        func(context.Context, *lib.Markdown) (*lib.Result, error)
	runMutex       sync.RWMutex
	runArgsForCall []struct {
		arg1 context.Context
		arg2 *lib.Markdown
	}
	runReturns struct {
		result1 *lib.Result
		result2 error
	}
	runReturnsOnCall map[int]struct {
		result1 *lib.Result
		result2 error
	}
	ShouldRunStub        func(context.Context, *lib.Markdown) (bool, error)
	shouldRunMutex       sync.RWMutex
	shouldRunArgsForCall []struct {
		arg1 context.Context
		arg2 *lib.Markdown
	}
	shouldRunReturns struct {
		result1 bool
		result2 error
	}
	shouldRunReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *AgentStep) Name() string {
	fake.nameMutex.Lock()
	ret, specificReturn := fake.nameReturnsOnCall[len(fake.nameArgsForCall)]
	fake.nameArgsForCall = append(fake.nameArgsForCall, struct {
	}{})
	stub := fake.NameStub
	fakeReturns := fake.nameReturns
	fake.recordInvocation("Name", []interface{}{})
	fake.nameMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *AgentStep) NameCallCount() int {
	fake.nameMutex.RLock()
	defer fake.nameMutex.RUnlock()
	return len(fake.nameArgsForCall)
}

func (fake *AgentStep) NameCalls(stub func() string) {
	fake.nameMutex.Lock()
	defer fake.nameMutex.Unlock()
	fake.NameStub = stub
}

func (fake *AgentStep) NameReturns(result1 string) {
	fake.nameMutex.Lock()
	defer fake.nameMutex.Unlock()
	fake.NameStub = nil
	fake.nameReturns = struct {
		result1 string
	}{result1}
}

func (fake *AgentStep) NameReturnsOnCall(i int, result1 string) {
	fake.nameMutex.Lock()
	defer fake.nameMutex.Unlock()
	fake.NameStub = nil
	if fake.nameReturnsOnCall == nil {
		fake.nameReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.nameReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *AgentStep) Run(arg1 context.Context, arg2 *lib.Markdown) (*lib.Result, error) {
	fake.runMutex.Lock()
	ret, specificReturn := fake.runReturnsOnCall[len(fake.runArgsForCall)]
	fake.runArgsForCall = append(fake.runArgsForCall, struct {
		arg1 context.Context
		arg2 *lib.Markdown
	}{arg1, arg2})
	stub := fake.RunStub
	fakeReturns := fake.runReturns
	fake.recordInvocation("Run", []interface{}{arg1, arg2})
	fake.runMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *AgentStep) RunCallCount() int {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return len(fake.runArgsForCall)
}

func (fake *AgentStep) RunCalls(stub func(context.Context, *lib.Markdown) (*lib.Result, error)) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = stub
}

func (fake *AgentStep) RunArgsForCall(i int) (context.Context, *lib.Markdown) {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	argsForCall := fake.runArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *AgentStep) RunReturns(result1 *lib.Result, result2 error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = nil
	fake.runReturns = struct {
		result1 *lib.Result
		result2 error
	}{result1, result2}
}

func (fake *AgentStep) RunReturnsOnCall(i int, result1 *lib.Result, result2 error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = nil
	if fake.runReturnsOnCall == nil {
		fake.runReturnsOnCall = make(map[int]struct {
			result1 *lib.Result
			result2 error
		})
	}
	fake.runReturnsOnCall[i] = struct {
		result1 *lib.Result
		result2 error
	}{result1, result2}
}

func (fake *AgentStep) ShouldRun(arg1 context.Context, arg2 *lib.Markdown) (bool, error) {
	fake.shouldRunMutex.Lock()
	ret, specificReturn := fake.shouldRunReturnsOnCall[len(fake.shouldRunArgsForCall)]
	fake.shouldRunArgsForCall = append(fake.shouldRunArgsForCall, struct {
		arg1 context.Context
		arg2 *lib.Markdown
	}{arg1, arg2})
	stub := fake.ShouldRunStub
	fakeReturns := fake.shouldRunReturns
	fake.recordInvocation("ShouldRun", []interface{}{arg1, arg2})
	fake.shouldRunMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *AgentStep) ShouldRunCallCount() int {
	fake.shouldRunMutex.RLock()
	defer fake.shouldRunMutex.RUnlock()
	return len(fake.shouldRunArgsForCall)
}

func (fake *AgentStep) ShouldRunCalls(stub func(context.Context, *lib.Markdown) (bool, error)) {
	fake.shouldRunMutex.Lock()
	defer fake.shouldRunMutex.Unlock()
	fake.ShouldRunStub = stub
}

func (fake *AgentStep) ShouldRunArgsForCall(i int) (context.Context, *lib.Markdown) {
	fake.shouldRunMutex.RLock()
	defer fake.shouldRunMutex.RUnlock()
	argsForCall := fake.shouldRunArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *AgentStep) ShouldRunReturns(result1 bool, result2 error) {
	fake.shouldRunMutex.Lock()
	defer fake.shouldRunMutex.Unlock()
	fake.ShouldRunStub = nil
	fake.shouldRunReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *AgentStep) ShouldRunReturnsOnCall(i int, result1 bool, result2 error) {
	fake.shouldRunMutex.Lock()
	defer fake.shouldRunMutex.Unlock()
	fake.ShouldRunStub = nil
	if fake.shouldRunReturnsOnCall == nil {
		fake.shouldRunReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.shouldRunReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *AgentStep) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *AgentStep) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ lib.Step = new(AgentStep)
