// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/agent/lib/claude"
)

type ClaudePluginInstaller struct {
	EnsureInstalledStub        func(context.Context, []claude.PluginSpec) error
	ensureInstalledMutex       sync.RWMutex
	ensureInstalledArgsForCall []struct {
		arg1 context.Context
		arg2 []claude.PluginSpec
	}
	ensureInstalledReturns struct {
		result1 error
	}
	ensureInstalledReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ClaudePluginInstaller) EnsureInstalled(arg1 context.Context, arg2 []claude.PluginSpec) error {
	var arg2Copy []claude.PluginSpec
	if arg2 != nil {
		arg2Copy = make([]claude.PluginSpec, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.ensureInstalledMutex.Lock()
	ret, specificReturn := fake.ensureInstalledReturnsOnCall[len(fake.ensureInstalledArgsForCall)]
	fake.ensureInstalledArgsForCall = append(fake.ensureInstalledArgsForCall, struct {
		arg1 context.Context
		arg2 []claude.PluginSpec
	}{arg1, arg2Copy})
	stub := fake.EnsureInstalledStub
	fakeReturns := fake.ensureInstalledReturns
	fake.recordInvocation("EnsureInstalled", []interface{}{arg1, arg2Copy})
	fake.ensureInstalledMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ClaudePluginInstaller) EnsureInstalledCallCount() int {
	fake.ensureInstalledMutex.RLock()
	defer fake.ensureInstalledMutex.RUnlock()
	return len(fake.ensureInstalledArgsForCall)
}

func (fake *ClaudePluginInstaller) EnsureInstalledCalls(stub func(context.Context, []claude.PluginSpec) error) {
	fake.ensureInstalledMutex.Lock()
	defer fake.ensureInstalledMutex.Unlock()
	fake.EnsureInstalledStub = stub
}

func (fake *ClaudePluginInstaller) EnsureInstalledArgsForCall(i int) (context.Context, []claude.PluginSpec) {
	fake.ensureInstalledMutex.RLock()
	defer fake.ensureInstalledMutex.RUnlock()
	argsForCall := fake.ensureInstalledArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ClaudePluginInstaller) EnsureInstalledReturns(result1 error) {
	fake.ensureInstalledMutex.Lock()
	defer fake.ensureInstalledMutex.Unlock()
	fake.EnsureInstalledStub = nil
	fake.ensureInstalledReturns = struct {
		result1 error
	}{result1}
}

func (fake *ClaudePluginInstaller) EnsureInstalledReturnsOnCall(i int, result1 error) {
	fake.ensureInstalledMutex.Lock()
	defer fake.ensureInstalledMutex.Unlock()
	fake.EnsureInstalledStub = nil
	if fake.ensureInstalledReturnsOnCall == nil {
		fake.ensureInstalledReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.ensureInstalledReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *ClaudePluginInstaller) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ClaudePluginInstaller) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ claude.PluginInstaller = new(ClaudePluginInstaller)
