// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"
	"time"

	lib "github.com/bborbe/agent"
	"github.com/bborbe/agent/metrics"
)

type JobMetrics struct {
	RecordDurationStub        func(time.Duration)
	recordDurationMutex       sync.RWMutex
	recordDurationArgsForCall []struct {
		arg1 time.Duration
	}
	RecordRunStub        func(lib.AgentStatus)
	recordRunMutex       sync.RWMutex
	recordRunArgsForCall []struct {
		arg1 lib.AgentStatus
	}
	RecordUsageStub        func(metrics.JobUsage)
	recordUsageMutex       sync.RWMutex
	recordUsageArgsForCall []struct {
		arg1 metrics.JobUsage
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *JobMetrics) RecordDuration(arg1 time.Duration) {
	fake.recordDurationMutex.Lock()
	fake.recordDurationArgsForCall = append(fake.recordDurationArgsForCall, struct {
		arg1 time.Duration
	}{arg1})
	stub := fake.RecordDurationStub
	fake.recordInvocation("RecordDuration", []interface{}{arg1})
	fake.recordDurationMutex.Unlock()
	if stub != nil {
		fake.RecordDurationStub(arg1)
	}
}

func (fake *JobMetrics) RecordDurationCallCount() int {
	fake.recordDurationMutex.RLock()
	defer fake.recordDurationMutex.RUnlock()
	return len(fake.recordDurationArgsForCall)
}

func (fake *JobMetrics) RecordDurationCalls(stub func(time.Duration)) {
	fake.recordDurationMutex.Lock()
	defer fake.recordDurationMutex.Unlock()
	fake.RecordDurationStub = stub
}

func (fake *JobMetrics) RecordDurationArgsForCall(i int) time.Duration {
	fake.recordDurationMutex.RLock()
	defer fake.recordDurationMutex.RUnlock()
	argsForCall := fake.recordDurationArgsForCall[i]
	return argsForCall.arg1
}

func (fake *JobMetrics) RecordRun(arg1 lib.AgentStatus) {
	fake.recordRunMutex.Lock()
	fake.recordRunArgsForCall = append(fake.recordRunArgsForCall, struct {
		arg1 lib.AgentStatus
	}{arg1})
	stub := fake.RecordRunStub
	fake.recordInvocation("RecordRun", []interface{}{arg1})
	fake.recordRunMutex.Unlock()
	if stub != nil {
		fake.RecordRunStub(arg1)
	}
}

func (fake *JobMetrics) RecordRunCallCount() int {
	fake.recordRunMutex.RLock()
	defer fake.recordRunMutex.RUnlock()
	return len(fake.recordRunArgsForCall)
}

func (fake *JobMetrics) RecordRunCalls(stub func(lib.AgentStatus)) {
	fake.recordRunMutex.Lock()
	defer fake.recordRunMutex.Unlock()
	fake.RecordRunStub = stub
}

func (fake *JobMetrics) RecordRunArgsForCall(i int) lib.AgentStatus {
	fake.recordRunMutex.RLock()
	defer fake.recordRunMutex.RUnlock()
	argsForCall := fake.recordRunArgsForCall[i]
	return argsForCall.arg1
}

func (fake *JobMetrics) RecordUsage(arg1 metrics.JobUsage) {
	fake.recordUsageMutex.Lock()
	fake.recordUsageArgsForCall = append(fake.recordUsageArgsForCall, struct {
		arg1 metrics.JobUsage
	}{arg1})
	stub := fake.RecordUsageStub
	fake.recordInvocation("RecordUsage", []interface{}{arg1})
	fake.recordUsageMutex.Unlock()
	if stub != nil {
		fake.RecordUsageStub(arg1)
	}
}

func (fake *JobMetrics) RecordUsageCallCount() int {
	fake.recordUsageMutex.RLock()
	defer fake.recordUsageMutex.RUnlock()
	return len(fake.recordUsageArgsForCall)
}

func (fake *JobMetrics) RecordUsageCalls(stub func(metrics.JobUsage)) {
	fake.recordUsageMutex.Lock()
	defer fake.recordUsageMutex.Unlock()
	fake.RecordUsageStub = stub
}

func (fake *JobMetrics) RecordUsageArgsForCall(i int) metrics.JobUsage {
	fake.recordUsageMutex.RLock()
	defer fake.recordUsageMutex.RUnlock()
	argsForCall := fake.recordUsageArgsForCall[i]
	return argsForCall.arg1
}

func (fake *JobMetrics) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *JobMetrics) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ metrics.JobMetrics = new(JobMetrics)
