// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	context "context"
	time "time"

	apisagentsbborbedevv1 "github.com/bborbe/agent/task/executor/k8s/apis/agents.bborbe.dev/v1"
	versioned "github.com/bborbe/agent/task/executor/k8s/client/clientset/versioned"
	internalinterfaces "github.com/bborbe/agent/task/executor/k8s/client/informers/externalversions/internalinterfaces"
	agentsbborbedevv1 "github.com/bborbe/agent/task/executor/k8s/client/listers/agents.bborbe.dev/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AgentConfigInformer provides access to a shared informer and lister for
// AgentConfigs.
type AgentConfigInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() agentsbborbedevv1.AgentConfigLister
}

type agentConfigInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAgentConfigInformer constructs a new informer for AgentConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAgentConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAgentConfigInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAgentConfigInformer constructs a new informer for AgentConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAgentConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AgentsV1().AgentConfigs(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AgentsV1().AgentConfigs(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AgentsV1().AgentConfigs(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AgentsV1().AgentConfigs(namespace).Watch(ctx, options)
			},
		}, client),
		&apisagentsbborbedevv1.AgentConfig{},
		resyncPeriod,
		indexers,
	)
}

func (f *agentConfigInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAgentConfigInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *agentConfigInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisagentsbborbedevv1.AgentConfig{}, f.defaultInformer)
}

func (f *agentConfigInformer) Lister() agentsbborbedevv1.AgentConfigLister {
	return agentsbborbedevv1.NewAgentConfigLister(f.Informer().GetIndexer())
}
