// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// AgentResourcesApplyConfiguration represents a declarative configuration of the AgentResources type for use
// with apply.
//
// AgentResources holds optional resource requests for the agent container.
type AgentResourcesApplyConfiguration struct {
	// CPU is the CPU resource request (e.g. "500m").
	CPU *string `json:"cpu,omitempty"`
	// Memory is the memory resource request (e.g. "256Mi").
	Memory *string `json:"memory,omitempty"`
	// EphemeralStorage is the ephemeral storage request (e.g. "1Gi").
	EphemeralStorage *string `json:"ephemeral-storage,omitempty"`
}

// AgentResourcesApplyConfiguration constructs a declarative configuration of the AgentResources type for use with
// apply.
func AgentResources() *AgentResourcesApplyConfiguration {
	return &AgentResourcesApplyConfiguration{}
}

// WithCPU sets the CPU field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CPU field is set to the value of the last call.
func (b *AgentResourcesApplyConfiguration) WithCPU(value string) *AgentResourcesApplyConfiguration {
	b.CPU = &value
	return b
}

// WithMemory sets the Memory field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Memory field is set to the value of the last call.
func (b *AgentResourcesApplyConfiguration) WithMemory(value string) *AgentResourcesApplyConfiguration {
	b.Memory = &value
	return b
}

// WithEphemeralStorage sets the EphemeralStorage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EphemeralStorage field is set to the value of the last call.
func (b *AgentResourcesApplyConfiguration) WithEphemeralStorage(value string) *AgentResourcesApplyConfiguration {
	b.EphemeralStorage = &value
	return b
}
