// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	agentsbborbedevv1 "github.com/bborbe/agent/task/executor/k8s/apis/agents.bborbe.dev/v1"
	applyconfigurationagentsbborbedevv1 "github.com/bborbe/agent/task/executor/k8s/client/applyconfiguration/agents.bborbe.dev/v1"
	scheme "github.com/bborbe/agent/task/executor/k8s/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// AgentConfigsGetter has a method to return a AgentConfigInterface.
// A group's client should implement this interface.
type AgentConfigsGetter interface {
	AgentConfigs(namespace string) AgentConfigInterface
}

// AgentConfigInterface has methods to work with AgentConfig resources.
type AgentConfigInterface interface {
	Create(ctx context.Context, agentConfig *agentsbborbedevv1.AgentConfig, opts metav1.CreateOptions) (*agentsbborbedevv1.AgentConfig, error)
	Update(ctx context.Context, agentConfig *agentsbborbedevv1.AgentConfig, opts metav1.UpdateOptions) (*agentsbborbedevv1.AgentConfig, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*agentsbborbedevv1.AgentConfig, error)
	List(ctx context.Context, opts metav1.ListOptions) (*agentsbborbedevv1.AgentConfigList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *agentsbborbedevv1.AgentConfig, err error)
	Apply(ctx context.Context, agentConfig *applyconfigurationagentsbborbedevv1.AgentConfigApplyConfiguration, opts metav1.ApplyOptions) (result *agentsbborbedevv1.AgentConfig, err error)
	AgentConfigExpansion
}

// agentConfigs implements AgentConfigInterface
type agentConfigs struct {
	*gentype.ClientWithListAndApply[*agentsbborbedevv1.AgentConfig, *agentsbborbedevv1.AgentConfigList, *applyconfigurationagentsbborbedevv1.AgentConfigApplyConfiguration]
}

// newAgentConfigs returns a AgentConfigs
func newAgentConfigs(c *AgentsV1Client, namespace string) *agentConfigs {
	return &agentConfigs{
		gentype.NewClientWithListAndApply[*agentsbborbedevv1.AgentConfig, *agentsbborbedevv1.AgentConfigList, *applyconfigurationagentsbborbedevv1.AgentConfigApplyConfiguration](
			"agentconfigs",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *agentsbborbedevv1.AgentConfig { return &agentsbborbedevv1.AgentConfig{} },
			func() *agentsbborbedevv1.AgentConfigList { return &agentsbborbedevv1.AgentConfigList{} },
		),
	}
}
