// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/bborbe/agent/task/executor/k8s/client/clientset/versioned/typed/agents.bborbe.dev/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeAgentsV1 struct {
	*testing.Fake
}

func (c *FakeAgentsV1) AgentConfigs(namespace string) v1.AgentConfigInterface {
	return newFakeAgentConfigs(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeAgentsV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
