// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/bborbe/agent/task/executor/k8s/apis/agents.bborbe.dev/v1"
	agentsbborbedevv1 "github.com/bborbe/agent/task/executor/k8s/client/applyconfiguration/agents.bborbe.dev/v1"
	typedagentsbborbedevv1 "github.com/bborbe/agent/task/executor/k8s/client/clientset/versioned/typed/agents.bborbe.dev/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeAgentConfigs implements AgentConfigInterface
type fakeAgentConfigs struct {
	*gentype.FakeClientWithListAndApply[*v1.AgentConfig, *v1.AgentConfigList, *agentsbborbedevv1.AgentConfigApplyConfiguration]
	Fake *FakeAgentsV1
}

func newFakeAgentConfigs(fake *FakeAgentsV1, namespace string) typedagentsbborbedevv1.AgentConfigInterface {
	return &fakeAgentConfigs{
		gentype.NewFakeClientWithListAndApply[*v1.AgentConfig, *v1.AgentConfigList, *agentsbborbedevv1.AgentConfigApplyConfiguration](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("agentconfigs"),
			v1.SchemeGroupVersion.WithKind("AgentConfig"),
			func() *v1.AgentConfig { return &v1.AgentConfig{} },
			func() *v1.AgentConfigList { return &v1.AgentConfigList{} },
			func(dst, src *v1.AgentConfigList) { dst.ListMeta = src.ListMeta },
			func(list *v1.AgentConfigList) []*v1.AgentConfig { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.AgentConfigList, items []*v1.AgentConfig) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
