// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/agent/task/controller/pkg/gitclient"
)

type FakeGitClient struct {
	EnsureClonedStub        func(context.Context) error
	ensureClonedMutex       sync.RWMutex
	ensureClonedArgsForCall []struct {
		arg1 context.Context
	}
	ensureClonedReturns struct {
		result1 error
	}
	ensureClonedReturnsOnCall map[int]struct {
		result1 error
	}
	PathStub        func() string
	pathMutex       sync.RWMutex
	pathArgsForCall []struct {
	}
	pathReturns struct {
		result1 string
	}
	pathReturnsOnCall map[int]struct {
		result1 string
	}
	PullStub        func(context.Context) error
	pullMutex       sync.RWMutex
	pullArgsForCall []struct {
		arg1 context.Context
	}
	pullReturns struct {
		result1 error
	}
	pullReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGitClient) EnsureCloned(arg1 context.Context) error {
	fake.ensureClonedMutex.Lock()
	ret, specificReturn := fake.ensureClonedReturnsOnCall[len(fake.ensureClonedArgsForCall)]
	fake.ensureClonedArgsForCall = append(fake.ensureClonedArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.EnsureClonedStub
	fakeReturns := fake.ensureClonedReturns
	fake.recordInvocation("EnsureCloned", []interface{}{arg1})
	fake.ensureClonedMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGitClient) EnsureClonedCallCount() int {
	fake.ensureClonedMutex.RLock()
	defer fake.ensureClonedMutex.RUnlock()
	return len(fake.ensureClonedArgsForCall)
}

func (fake *FakeGitClient) EnsureClonedCalls(stub func(context.Context) error) {
	fake.ensureClonedMutex.Lock()
	defer fake.ensureClonedMutex.Unlock()
	fake.EnsureClonedStub = stub
}

func (fake *FakeGitClient) EnsureClonedArgsForCall(i int) context.Context {
	fake.ensureClonedMutex.RLock()
	defer fake.ensureClonedMutex.RUnlock()
	argsForCall := fake.ensureClonedArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeGitClient) EnsureClonedReturns(result1 error) {
	fake.ensureClonedMutex.Lock()
	defer fake.ensureClonedMutex.Unlock()
	fake.EnsureClonedStub = nil
	fake.ensureClonedReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeGitClient) EnsureClonedReturnsOnCall(i int, result1 error) {
	fake.ensureClonedMutex.Lock()
	defer fake.ensureClonedMutex.Unlock()
	fake.EnsureClonedStub = nil
	if fake.ensureClonedReturnsOnCall == nil {
		fake.ensureClonedReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.ensureClonedReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeGitClient) Path() string {
	fake.pathMutex.Lock()
	ret, specificReturn := fake.pathReturnsOnCall[len(fake.pathArgsForCall)]
	fake.pathArgsForCall = append(fake.pathArgsForCall, struct {
	}{})
	stub := fake.PathStub
	fakeReturns := fake.pathReturns
	fake.recordInvocation("Path", []interface{}{})
	fake.pathMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGitClient) PathCallCount() int {
	fake.pathMutex.RLock()
	defer fake.pathMutex.RUnlock()
	return len(fake.pathArgsForCall)
}

func (fake *FakeGitClient) PathCalls(stub func() string) {
	fake.pathMutex.Lock()
	defer fake.pathMutex.Unlock()
	fake.PathStub = stub
}

func (fake *FakeGitClient) PathReturns(result1 string) {
	fake.pathMutex.Lock()
	defer fake.pathMutex.Unlock()
	fake.PathStub = nil
	fake.pathReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGitClient) PathReturnsOnCall(i int, result1 string) {
	fake.pathMutex.Lock()
	defer fake.pathMutex.Unlock()
	fake.PathStub = nil
	if fake.pathReturnsOnCall == nil {
		fake.pathReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.pathReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGitClient) Pull(arg1 context.Context) error {
	fake.pullMutex.Lock()
	ret, specificReturn := fake.pullReturnsOnCall[len(fake.pullArgsForCall)]
	fake.pullArgsForCall = append(fake.pullArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.PullStub
	fakeReturns := fake.pullReturns
	fake.recordInvocation("Pull", []interface{}{arg1})
	fake.pullMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGitClient) PullCallCount() int {
	fake.pullMutex.RLock()
	defer fake.pullMutex.RUnlock()
	return len(fake.pullArgsForCall)
}

func (fake *FakeGitClient) PullCalls(stub func(context.Context) error) {
	fake.pullMutex.Lock()
	defer fake.pullMutex.Unlock()
	fake.PullStub = stub
}

func (fake *FakeGitClient) PullArgsForCall(i int) context.Context {
	fake.pullMutex.RLock()
	defer fake.pullMutex.RUnlock()
	argsForCall := fake.pullArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeGitClient) PullReturns(result1 error) {
	fake.pullMutex.Lock()
	defer fake.pullMutex.Unlock()
	fake.PullStub = nil
	fake.pullReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeGitClient) PullReturnsOnCall(i int, result1 error) {
	fake.pullMutex.Lock()
	defer fake.pullMutex.Unlock()
	fake.PullStub = nil
	if fake.pullReturnsOnCall == nil {
		fake.pullReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.pullReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeGitClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGitClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ gitclient.GitClient = new(FakeGitClient)
