// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/agent/task/controller/pkg/gitclient"
)

type FakeGitClient struct {
	AtomicReadModifyWriteAndCommitPushStub        func(context.Context, string, func(current []byte) ([]byte, error), string) error
	atomicReadModifyWriteAndCommitPushMutex       sync.RWMutex
	atomicReadModifyWriteAndCommitPushArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 func(current []byte) ([]byte, error)
		arg4 string
	}
	atomicReadModifyWriteAndCommitPushReturns struct {
		result1 error
	}
	atomicReadModifyWriteAndCommitPushReturnsOnCall map[int]struct {
		result1 error
	}
	AtomicWriteAndCommitPushStub        func(context.Context, string, []byte, string) error
	atomicWriteAndCommitPushMutex       sync.RWMutex
	atomicWriteAndCommitPushArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 []byte
		arg4 string
	}
	atomicWriteAndCommitPushReturns struct {
		result1 error
	}
	atomicWriteAndCommitPushReturnsOnCall map[int]struct {
		result1 error
	}
	CommitAndPushStub        func(context.Context, string) error
	commitAndPushMutex       sync.RWMutex
	commitAndPushArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	commitAndPushReturns struct {
		result1 error
	}
	commitAndPushReturnsOnCall map[int]struct {
		result1 error
	}
	EnsureClonedStub        func(context.Context) error
	ensureClonedMutex       sync.RWMutex
	ensureClonedArgsForCall []struct {
		arg1 context.Context
	}
	ensureClonedReturns struct {
		result1 error
	}
	ensureClonedReturnsOnCall map[int]struct {
		result1 error
	}
	PathStub        func() string
	pathMutex       sync.RWMutex
	pathArgsForCall []struct {
	}
	pathReturns struct {
		result1 string
	}
	pathReturnsOnCall map[int]struct {
		result1 string
	}
	PullStub        func(context.Context) error
	pullMutex       sync.RWMutex
	pullArgsForCall []struct {
		arg1 context.Context
	}
	pullReturns struct {
		result1 error
	}
	pullReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGitClient) AtomicReadModifyWriteAndCommitPush(arg1 context.Context, arg2 string, arg3 func(current []byte) ([]byte, error), arg4 string) error {
	fake.atomicReadModifyWriteAndCommitPushMutex.Lock()
	ret, specificReturn := fake.atomicReadModifyWriteAndCommitPushReturnsOnCall[len(fake.atomicReadModifyWriteAndCommitPushArgsForCall)]
	fake.atomicReadModifyWriteAndCommitPushArgsForCall = append(fake.atomicReadModifyWriteAndCommitPushArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 func(current []byte) ([]byte, error)
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.AtomicReadModifyWriteAndCommitPushStub
	fakeReturns := fake.atomicReadModifyWriteAndCommitPushReturns
	fake.recordInvocation("AtomicReadModifyWriteAndCommitPush", []interface{}{arg1, arg2, arg3, arg4})
	fake.atomicReadModifyWriteAndCommitPushMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGitClient) AtomicReadModifyWriteAndCommitPushCallCount() int {
	fake.atomicReadModifyWriteAndCommitPushMutex.RLock()
	defer fake.atomicReadModifyWriteAndCommitPushMutex.RUnlock()
	return len(fake.atomicReadModifyWriteAndCommitPushArgsForCall)
}

func (fake *FakeGitClient) AtomicReadModifyWriteAndCommitPushCalls(stub func(context.Context, string, func(current []byte) ([]byte, error), string) error) {
	fake.atomicReadModifyWriteAndCommitPushMutex.Lock()
	defer fake.atomicReadModifyWriteAndCommitPushMutex.Unlock()
	fake.AtomicReadModifyWriteAndCommitPushStub = stub
}

func (fake *FakeGitClient) AtomicReadModifyWriteAndCommitPushArgsForCall(i int) (context.Context, string, func(current []byte) ([]byte, error), string) {
	fake.atomicReadModifyWriteAndCommitPushMutex.RLock()
	defer fake.atomicReadModifyWriteAndCommitPushMutex.RUnlock()
	argsForCall := fake.atomicReadModifyWriteAndCommitPushArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeGitClient) AtomicReadModifyWriteAndCommitPushReturns(result1 error) {
	fake.atomicReadModifyWriteAndCommitPushMutex.Lock()
	defer fake.atomicReadModifyWriteAndCommitPushMutex.Unlock()
	fake.AtomicReadModifyWriteAndCommitPushStub = nil
	fake.atomicReadModifyWriteAndCommitPushReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeGitClient) AtomicReadModifyWriteAndCommitPushReturnsOnCall(i int, result1 error) {
	fake.atomicReadModifyWriteAndCommitPushMutex.Lock()
	defer fake.atomicReadModifyWriteAndCommitPushMutex.Unlock()
	fake.AtomicReadModifyWriteAndCommitPushStub = nil
	if fake.atomicReadModifyWriteAndCommitPushReturnsOnCall == nil {
		fake.atomicReadModifyWriteAndCommitPushReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.atomicReadModifyWriteAndCommitPushReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeGitClient) AtomicWriteAndCommitPush(arg1 context.Context, arg2 string, arg3 []byte, arg4 string) error {
	var arg3Copy []byte
	if arg3 != nil {
		arg3Copy = make([]byte, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.atomicWriteAndCommitPushMutex.Lock()
	ret, specificReturn := fake.atomicWriteAndCommitPushReturnsOnCall[len(fake.atomicWriteAndCommitPushArgsForCall)]
	fake.atomicWriteAndCommitPushArgsForCall = append(fake.atomicWriteAndCommitPushArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 []byte
		arg4 string
	}{arg1, arg2, arg3Copy, arg4})
	stub := fake.AtomicWriteAndCommitPushStub
	fakeReturns := fake.atomicWriteAndCommitPushReturns
	fake.recordInvocation("AtomicWriteAndCommitPush", []interface{}{arg1, arg2, arg3Copy, arg4})
	fake.atomicWriteAndCommitPushMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGitClient) AtomicWriteAndCommitPushCallCount() int {
	fake.atomicWriteAndCommitPushMutex.RLock()
	defer fake.atomicWriteAndCommitPushMutex.RUnlock()
	return len(fake.atomicWriteAndCommitPushArgsForCall)
}

func (fake *FakeGitClient) AtomicWriteAndCommitPushCalls(stub func(context.Context, string, []byte, string) error) {
	fake.atomicWriteAndCommitPushMutex.Lock()
	defer fake.atomicWriteAndCommitPushMutex.Unlock()
	fake.AtomicWriteAndCommitPushStub = stub
}

func (fake *FakeGitClient) AtomicWriteAndCommitPushArgsForCall(i int) (context.Context, string, []byte, string) {
	fake.atomicWriteAndCommitPushMutex.RLock()
	defer fake.atomicWriteAndCommitPushMutex.RUnlock()
	argsForCall := fake.atomicWriteAndCommitPushArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeGitClient) AtomicWriteAndCommitPushReturns(result1 error) {
	fake.atomicWriteAndCommitPushMutex.Lock()
	defer fake.atomicWriteAndCommitPushMutex.Unlock()
	fake.AtomicWriteAndCommitPushStub = nil
	fake.atomicWriteAndCommitPushReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeGitClient) AtomicWriteAndCommitPushReturnsOnCall(i int, result1 error) {
	fake.atomicWriteAndCommitPushMutex.Lock()
	defer fake.atomicWriteAndCommitPushMutex.Unlock()
	fake.AtomicWriteAndCommitPushStub = nil
	if fake.atomicWriteAndCommitPushReturnsOnCall == nil {
		fake.atomicWriteAndCommitPushReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.atomicWriteAndCommitPushReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeGitClient) CommitAndPush(arg1 context.Context, arg2 string) error {
	fake.commitAndPushMutex.Lock()
	ret, specificReturn := fake.commitAndPushReturnsOnCall[len(fake.commitAndPushArgsForCall)]
	fake.commitAndPushArgsForCall = append(fake.commitAndPushArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.CommitAndPushStub
	fakeReturns := fake.commitAndPushReturns
	fake.recordInvocation("CommitAndPush", []interface{}{arg1, arg2})
	fake.commitAndPushMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGitClient) CommitAndPushCallCount() int {
	fake.commitAndPushMutex.RLock()
	defer fake.commitAndPushMutex.RUnlock()
	return len(fake.commitAndPushArgsForCall)
}

func (fake *FakeGitClient) CommitAndPushCalls(stub func(context.Context, string) error) {
	fake.commitAndPushMutex.Lock()
	defer fake.commitAndPushMutex.Unlock()
	fake.CommitAndPushStub = stub
}

func (fake *FakeGitClient) CommitAndPushArgsForCall(i int) (context.Context, string) {
	fake.commitAndPushMutex.RLock()
	defer fake.commitAndPushMutex.RUnlock()
	argsForCall := fake.commitAndPushArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeGitClient) CommitAndPushReturns(result1 error) {
	fake.commitAndPushMutex.Lock()
	defer fake.commitAndPushMutex.Unlock()
	fake.CommitAndPushStub = nil
	fake.commitAndPushReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeGitClient) CommitAndPushReturnsOnCall(i int, result1 error) {
	fake.commitAndPushMutex.Lock()
	defer fake.commitAndPushMutex.Unlock()
	fake.CommitAndPushStub = nil
	if fake.commitAndPushReturnsOnCall == nil {
		fake.commitAndPushReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.commitAndPushReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeGitClient) EnsureCloned(arg1 context.Context) error {
	fake.ensureClonedMutex.Lock()
	ret, specificReturn := fake.ensureClonedReturnsOnCall[len(fake.ensureClonedArgsForCall)]
	fake.ensureClonedArgsForCall = append(fake.ensureClonedArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.EnsureClonedStub
	fakeReturns := fake.ensureClonedReturns
	fake.recordInvocation("EnsureCloned", []interface{}{arg1})
	fake.ensureClonedMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGitClient) EnsureClonedCallCount() int {
	fake.ensureClonedMutex.RLock()
	defer fake.ensureClonedMutex.RUnlock()
	return len(fake.ensureClonedArgsForCall)
}

func (fake *FakeGitClient) EnsureClonedCalls(stub func(context.Context) error) {
	fake.ensureClonedMutex.Lock()
	defer fake.ensureClonedMutex.Unlock()
	fake.EnsureClonedStub = stub
}

func (fake *FakeGitClient) EnsureClonedArgsForCall(i int) context.Context {
	fake.ensureClonedMutex.RLock()
	defer fake.ensureClonedMutex.RUnlock()
	argsForCall := fake.ensureClonedArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeGitClient) EnsureClonedReturns(result1 error) {
	fake.ensureClonedMutex.Lock()
	defer fake.ensureClonedMutex.Unlock()
	fake.EnsureClonedStub = nil
	fake.ensureClonedReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeGitClient) EnsureClonedReturnsOnCall(i int, result1 error) {
	fake.ensureClonedMutex.Lock()
	defer fake.ensureClonedMutex.Unlock()
	fake.EnsureClonedStub = nil
	if fake.ensureClonedReturnsOnCall == nil {
		fake.ensureClonedReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.ensureClonedReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeGitClient) Path() string {
	fake.pathMutex.Lock()
	ret, specificReturn := fake.pathReturnsOnCall[len(fake.pathArgsForCall)]
	fake.pathArgsForCall = append(fake.pathArgsForCall, struct {
	}{})
	stub := fake.PathStub
	fakeReturns := fake.pathReturns
	fake.recordInvocation("Path", []interface{}{})
	fake.pathMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGitClient) PathCallCount() int {
	fake.pathMutex.RLock()
	defer fake.pathMutex.RUnlock()
	return len(fake.pathArgsForCall)
}

func (fake *FakeGitClient) PathCalls(stub func() string) {
	fake.pathMutex.Lock()
	defer fake.pathMutex.Unlock()
	fake.PathStub = stub
}

func (fake *FakeGitClient) PathReturns(result1 string) {
	fake.pathMutex.Lock()
	defer fake.pathMutex.Unlock()
	fake.PathStub = nil
	fake.pathReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGitClient) PathReturnsOnCall(i int, result1 string) {
	fake.pathMutex.Lock()
	defer fake.pathMutex.Unlock()
	fake.PathStub = nil
	if fake.pathReturnsOnCall == nil {
		fake.pathReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.pathReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGitClient) Pull(arg1 context.Context) error {
	fake.pullMutex.Lock()
	ret, specificReturn := fake.pullReturnsOnCall[len(fake.pullArgsForCall)]
	fake.pullArgsForCall = append(fake.pullArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.PullStub
	fakeReturns := fake.pullReturns
	fake.recordInvocation("Pull", []interface{}{arg1})
	fake.pullMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGitClient) PullCallCount() int {
	fake.pullMutex.RLock()
	defer fake.pullMutex.RUnlock()
	return len(fake.pullArgsForCall)
}

func (fake *FakeGitClient) PullCalls(stub func(context.Context) error) {
	fake.pullMutex.Lock()
	defer fake.pullMutex.Unlock()
	fake.PullStub = stub
}

func (fake *FakeGitClient) PullArgsForCall(i int) context.Context {
	fake.pullMutex.RLock()
	defer fake.pullMutex.RUnlock()
	argsForCall := fake.pullArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeGitClient) PullReturns(result1 error) {
	fake.pullMutex.Lock()
	defer fake.pullMutex.Unlock()
	fake.PullStub = nil
	fake.pullReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeGitClient) PullReturnsOnCall(i int, result1 error) {
	fake.pullMutex.Lock()
	defer fake.pullMutex.Unlock()
	fake.PullStub = nil
	if fake.pullReturnsOnCall == nil {
		fake.pullReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.pullReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeGitClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGitClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ gitclient.GitClient = new(FakeGitClient)
