// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/agent/task/controller/pkg/scanner"
)

type FakeVaultScanner struct {
	ResultsStub        func() <-chan scanner.ScanResult
	resultsMutex       sync.RWMutex
	resultsArgsForCall []struct {
	}
	resultsReturns struct {
		result1 <-chan scanner.ScanResult
	}
	resultsReturnsOnCall map[int]struct {
		result1 <-chan scanner.ScanResult
	}
	RunStub        func(context.Context) error
	runMutex       sync.RWMutex
	runArgsForCall []struct {
		arg1 context.Context
	}
	runReturns struct {
		result1 error
	}
	runReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeVaultScanner) Results() <-chan scanner.ScanResult {
	fake.resultsMutex.Lock()
	ret, specificReturn := fake.resultsReturnsOnCall[len(fake.resultsArgsForCall)]
	fake.resultsArgsForCall = append(fake.resultsArgsForCall, struct {
	}{})
	stub := fake.ResultsStub
	fakeReturns := fake.resultsReturns
	fake.recordInvocation("Results", []interface{}{})
	fake.resultsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeVaultScanner) ResultsCallCount() int {
	fake.resultsMutex.RLock()
	defer fake.resultsMutex.RUnlock()
	return len(fake.resultsArgsForCall)
}

func (fake *FakeVaultScanner) ResultsCalls(stub func() <-chan scanner.ScanResult) {
	fake.resultsMutex.Lock()
	defer fake.resultsMutex.Unlock()
	fake.ResultsStub = stub
}

func (fake *FakeVaultScanner) ResultsReturns(result1 <-chan scanner.ScanResult) {
	fake.resultsMutex.Lock()
	defer fake.resultsMutex.Unlock()
	fake.ResultsStub = nil
	fake.resultsReturns = struct {
		result1 <-chan scanner.ScanResult
	}{result1}
}

func (fake *FakeVaultScanner) ResultsReturnsOnCall(i int, result1 <-chan scanner.ScanResult) {
	fake.resultsMutex.Lock()
	defer fake.resultsMutex.Unlock()
	fake.ResultsStub = nil
	if fake.resultsReturnsOnCall == nil {
		fake.resultsReturnsOnCall = make(map[int]struct {
			result1 <-chan scanner.ScanResult
		})
	}
	fake.resultsReturnsOnCall[i] = struct {
		result1 <-chan scanner.ScanResult
	}{result1}
}

func (fake *FakeVaultScanner) Run(arg1 context.Context) error {
	fake.runMutex.Lock()
	ret, specificReturn := fake.runReturnsOnCall[len(fake.runArgsForCall)]
	fake.runArgsForCall = append(fake.runArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.RunStub
	fakeReturns := fake.runReturns
	fake.recordInvocation("Run", []interface{}{arg1})
	fake.runMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeVaultScanner) RunCallCount() int {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return len(fake.runArgsForCall)
}

func (fake *FakeVaultScanner) RunCalls(stub func(context.Context) error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = stub
}

func (fake *FakeVaultScanner) RunArgsForCall(i int) context.Context {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	argsForCall := fake.runArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeVaultScanner) RunReturns(result1 error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = nil
	fake.runReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeVaultScanner) RunReturnsOnCall(i int, result1 error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = nil
	if fake.runReturnsOnCall == nil {
		fake.runReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.runReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeVaultScanner) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeVaultScanner) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ scanner.VaultScanner = new(FakeVaultScanner)
