// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	agentsbborbedevv1 "github.com/bborbe/agent/task/executor/k8s/apis/agents.bborbe.dev/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// AgentConfigLister helps list AgentConfigs.
// All objects returned here must be treated as read-only.
type AgentConfigLister interface {
	// List lists all AgentConfigs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*agentsbborbedevv1.AgentConfig, err error)
	// AgentConfigs returns an object that can list and get AgentConfigs.
	AgentConfigs(namespace string) AgentConfigNamespaceLister
	AgentConfigListerExpansion
}

// agentConfigLister implements the AgentConfigLister interface.
type agentConfigLister struct {
	listers.ResourceIndexer[*agentsbborbedevv1.AgentConfig]
}

// NewAgentConfigLister returns a new AgentConfigLister.
func NewAgentConfigLister(indexer cache.Indexer) AgentConfigLister {
	return &agentConfigLister{listers.New[*agentsbborbedevv1.AgentConfig](indexer, agentsbborbedevv1.Resource("agentconfig"))}
}

// AgentConfigs returns an object that can list and get AgentConfigs.
func (s *agentConfigLister) AgentConfigs(namespace string) AgentConfigNamespaceLister {
	return agentConfigNamespaceLister{listers.NewNamespaced[*agentsbborbedevv1.AgentConfig](s.ResourceIndexer, namespace)}
}

// AgentConfigNamespaceLister helps list and get AgentConfigs.
// All objects returned here must be treated as read-only.
type AgentConfigNamespaceLister interface {
	// List lists all AgentConfigs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*agentsbborbedevv1.AgentConfig, err error)
	// Get retrieves the AgentConfig from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*agentsbborbedevv1.AgentConfig, error)
	AgentConfigNamespaceListerExpansion
}

// agentConfigNamespaceLister implements the AgentConfigNamespaceLister
// interface.
type agentConfigNamespaceLister struct {
	listers.ResourceIndexer[*agentsbborbedevv1.AgentConfig]
}
