// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Code generated by lister-gen. DO NOT EDIT.

package v1

// AgentConfigListerExpansion allows custom methods to be added to
// AgentConfigLister.
type AgentConfigListerExpansion interface{}

// AgentConfigNamespaceListerExpansion allows custom methods to be added to
// AgentConfigNamespaceLister.
type AgentConfigNamespaceListerExpansion interface{}
